### ISSUE TITLE
Setup MobX and refactor existing code

### ISSUE THREAD

**Issue by Bertware** [oSoc18/OASIS#52]
We will use MobX to keep our state synchronized through the entire application. Therefore, we need to install the dependencies, create an observable class which will store our state, and rework existing logic to use this common state provider class.

Our common state class should include some fields:
- A private, unfiltered array of buildings.
- A public, filtered array of buildings.
- A public variable containing one building id (or null) for which details should be shown
- A public variable containing the display state, either details or list

**Tasks:**
- [x] Install MobX and MobX-react
- [x] Create `BuildingStore` as our state store.
- [x] Store the existing building array in the store. 
- [x] Rework the map to show the filtered array of buildings
- [x] Rework the sidebar to show the filtered array or single building depending on the display state

**Notes:**
Please don't forget to use clear variable naming and to use javadoc (`/** @param ... **/`) to document functions.
